### ISSUE TITLE
Failing to fetch new package version

### ISSUE THREAD

**Issue by bitomic** [bachmacintosh/need-npm-package-version-bump#25]
Hey!

I was looking for actions to do exactly what this one does, so great! But when I tried to use it, it reports:
```
Fetching Old Version from bitomic/mew/d0ccd1479c1e7501ba8b7b0a3cd22c94e56c010a...
Fetching New Version...
Versions fetched. Comparing...
Error: New package.json version 1.0.0 <= 1.0.0
```

The old version, indeed, has a `d0ccd` hash and version 1.0.0. But the new version seems to be wrong, since I updated it to 1.0.1 in a next commit for the pull request.

- **Pull request:** https://github.com/bitomic/mew/pull/31
- **Latest commit, which bumps the version:** https://github.com/bitomic/mew/pull/31/commits/cbec97d49e1d492623a294a52000303bd156c0a9
- **Action logs:** https://github.com/bitomic/mew/actions/runs/3391680335/jobs/5637108306

**Comment by bachmacintosh** [comment]
Hello, sorry for the delay.

This is a documentation mess-up on my part, and has to do with which commits are referenced by default in GitHub Actions.

Since you're using a `pull_request_target` trigger in your `require-version-bump.yml` workflow, the default ref used by your `checkout` action is actually the base branch (e.g. `main`) instead of the latest commit in the PR; this is among other somewhat sensible defaults to prevent PWN requests that can steal Secrets and other bad things, but it means in your case that the "new" `package.json` is just the old one with the same old version...

So there's a couple ways to approach the fix.

1. If you plan to keep your workflows separate, you can just change that `pull_request_target` event to a `pull_request` event. Then I would expect that your `checkout` would pull the ref of the latest PR commit. This is also good practice in terms of repo security, since `pull_request_target` should only be used for certain cases, namely needing access to Secrets or a permissive `GITHUB_TOKEN` when working with PRs in Actions.
2. If you plan to bring the version bump check into a workflow that *needs* `pull_request_target` (i.e. just have it separate for testing purposes right now), you'd need to make sure you're checking out the latest PR ref in your `checkout` step:

```yaml
- name: Checkout
   uses: actions/checkout@v3
   with:
     ref: ${{github.event.pull_request.head.ref}}
     repository: ${{github.event.pull_request.head.repo.full_name}}
```

Try one of the above on `require-version-bump.yml`, and maybe update one of the step names as well just so we can be sure your PR isn't running an old version of the workflow. Your test PR is gonna run the workflow in `main`, so it'll need to be updated in a separate commit/PR. Then if you update the test PR (e.g. to catch up with the base branch), I would expect its version bump check to now pass.

Hope that helps in explaining things. I'll be sure to call this out in the README once we're certain it resolves your issue. Any questions or if it still fails let me know.

**Comment by bitomic** [comment]
I wouldn't call this a delay, haha.

I admit I am somewhat newbie regarding workflow events, recently I had one thatwould only work with `pull_request_target` but not `pull_request` so I went using `_target` most of the times; thank you for the explanation!

Everything works fine now, thank you a lot! 😄
